### ISSUE TITLE
Question about GoCenter removal

### ISSUE THREAD

**Issue by elioengcomp** [yuuki/shawk#36]
Hi,

I'm from the GoCenter team and I saw on commit [c1e1b501](https://github.com/yuuki/shawk/commit/c1e1b50111ec2e7a27db3792044fe2200e2519b0) that you are not using GoCenter anymore because it does not host go-gnulib.

However I can see that module in the GoCenter UI and I was able to fetch the version you have in your go.mod file from there:

```
→ export GOPROXY=https://gocenter.io/

→ go get github.com/EricLagergren/go-gnulib@v0.0.0-20191129172535-039a51fc60f4
go: finding github.com/EricLagergren/go-gnulib v0.0.0-20191129172535-039a51fc60f4
go: downloading github.com/EricLagergren/go-gnulib v0.0.0-20191129172535-039a51fc60f4
go: extracting github.com/EricLagergren/go-gnulib v0.0.0-20191129172535-039a51fc60f4
```

Can you provide more information about what do you mean by GoCenter not hosting go-gnulib? We would like to understand your requirements better to see if there are opportunities to improve our center?

Best.

**Comment by yuuki** [comment]
@elioengcomp 

Thank you for your comment.

I'm sorry to say, I don't remember the situation that the Gocenter didn't working. Now, I noticed my misunderstanding thanks to your comment.  I will try the GoCenter again.

**Comment by elioengcomp** [comment]
Thanks @yuuki ,

Let me know if you still find any issues there.
